### ISSUE TITLE
v11.0 Migration Checklist

### ISSUE THREAD

**Issue by sudhir-serpentcs** [JayVora-SerpentCS/SerpentCS_Contributions-v8#148]
- [x] base_module_record
- [x] base_synchro
- [ ] city - [base_address_city](https://github.com/odoo/odoo/tree/11.0/addons/base_address_city) of Odoo base
- [ ] hr_applicant
- [ ] hr_grade_rank
- [ ] label - Jagdish
- [x] partner_credit_limit
- [x] project_detail_report - #149
- [x] project_kanban
- [x] project_task_detail_report
- [x] project_team - #151
- [ ] sale_cancel_reason - #145 [Canceled as it is contributed in OCA/sale-workflow]
- [x] sale_report_hide_price - #154
- [x] sale_restrict
- [x] sale_report_product_image - Depends on [web_tree_image](https://github.com/OCA/web/tree/10.0/web_tree_image) of OCA web
- [ ] web_digital_sign
- [ ] web_groupby_expand
- [ ] web_lead_funnel_chart
- [ ] web_one2many_kanban
- [ ] web_security_dialog
- [ ] web_widget_multi_image
- [ ] website_multi_image_zoom
- [ ] website_product_brand

**Comment by sudhir-serpentcs** [comment]
TODO:
sale_report_product_image module depends on web_tree_image of OCA web.
Once web_tree_image is migrated, add dependency and widget in sale_report_product_image module.
CC: @JayVora-SerpentCS

**Comment by sudhir-serpentcs** [comment]
base_address_city module of the base can replace the city module.
CC: @JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
@sudhir-serpentcs Jagdish is on label v11.

**Comment by sudhir-serpentcs** [comment]
Contributed sale_cancel_reason module in OCA sale-workflow.
[PR 559](https://github.com/OCA/sale-workflow/pull/559)
