### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by Chandresh-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#369]
# Modules to migrate

- [x] base_module_record - @Swapnesh-SerpentCS
- [x] **base_synchro** *Assigned to @Swapnesh-SerpentCS
- [x] **city** By @Vrushali-SerpentCS #405 
- [x] **hr_applicant** By @HarshK-SerpentCS #387 
- [x] **hr_grade_rank** By @HarshK-SerpentCS #380 
- [x] **import_export_templating** By @murtuzasaleh #390 
- [x] **label** By @Murtaza-SerpentCS #393 
- [x] **partner_credit_limit** By @HarshK-SerpentCS #383 
- [x] **project_detail_report** By @Vrushali-SerpentCS #406
- [x] **project_kanban** By @HarshK-SerpentCS #378 
- [x] **project_task_detail_report** By @HarshK-SerpentCS #382 
- [x] **project_team** By @Murtaza-SerpentCS #396 
- [x] **sale_product_smart_buttons** By to @HarshK-SerpentCS #381 
- [x] **sale_report_hide_price** By @HarshK-SerpentCS #385 
- [x] **sale_restrict** By to @HarshK-SerpentCS #379 
- [x] **sales_report_product_image** - By @ChavdaRiddhi #373 
- [x] **web_digital_sign** By @hpatelserpentcs #392 
- [ ] web_groupby_expand
- [x] **web_lead_funnel_chart** By @drashtipatel24 #399 
- [x] **web_one2many_kanban** By @drashtipatel24 #398 
- [x] **web_security_dialog** By @hpatelserpentcs #395 
- [x] **web_widget_multi_image** By @hpatelserpentcs #397
- [x] **website_product_brand** By @hpatelserpentcs #403

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS edit as done.

**Comment by Chandresh-SerpentCS** [comment]
> @Chandresh-SerpentCS edit as done.

Done.
