### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by Chandresh-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#500]
# Modules to migrate

- [ ] base_module_record
- [x] **base_synchro** Assigned to @ForamSerpentCS
- [ ] city
- [x] **hr_applicant** Assigned to @Chandresh-SerpentCS #522 
- [x] **hr_grade_rank** Assigned to @Chandresh-SerpentCS #521 
- [ ] **import_export_templating** Assigned to @Chandresh-SerpentCS
- [x] **label** Assigned to @Chandresh-SerpentCS #506 
- [x] **partner_credit_limit** Assigned to @Chandresh-SerpentCS #507 
- [X] **project_detail_report** #504 Done By @vimalpatelserpentcs
- [X] **project_kanban** #503 Done By @vimalpatelserpentcs
- [X] **project_task_detail_report** #505 Done By @vimalpatelserpentcs
- [X] **project_team** #502 Done By @vimalpatelserpentcs
- [x] **sale_product_smart_buttons** Assigned to @Chandresh-SerpentCS #517 
- [x] **sale_report_hide_price** Assigned to @Chandresh-SerpentCS #516 
- [x] **sale_restrict** Assigned to @Chandresh-SerpentCS #508 
- [x] **sales_report_product_image** Assigned to @Chandresh-SerpentCS #518 
- [x] **web_digital_sign** Assigned to @nikul-serpentcs
- [ ] web_groupby_expand
- [x] **web_lead_funnel_chart** #555 Assigned to @drashtipatel24 
- [ ] web_one2many_kanban
- [ ] web_security_dialog
- [ ] web_widget_multi_image
- [ ] website_product_brand
- [X] **ipushp** Assigned to @ForamSerpentCS #509

**Comment by JayVora-SerpentCS** [comment]
v14--> ipushp, base_synchro  @ForamSerpentCS
