### ISSUE TITLE
Migration to 17.0

### ISSUE THREAD

**Issue by Trivedi-Vacha-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#620]
Modules to migrate

- [ ] base_module_record
- [ ] base_synchro
- [ ] hr_applicant PR #649 
- [x] hr_grade_rank Assigned to @PratikVaza-SerpentCS PR #622 
- [ ] import_export_templating PR #649 
- [ ] label PR #648 
- [ ] partner_credit_limit
- [ ] project_detail_report Assigned to @PratikVaza-SerpentCS  PR #624 
- [ ] project_kanban Assigned to to Neel Patel PR #638 
- [ ] project_task_detail_report Assigned to @ Kaushik PR #639 
- [ ] project_team PR #621 
- [x] sale_product_smart_buttons Assigned to @PratikVaza-SerpentCS 
- [ ] sale_report_hide_price Assigned to @ Amisha PR #635 
- [ ] sale_restrict Assigned to @PratikVaza-SerpentCS PR #623 
- [ ] sales_report_product_image Assigned to @PratikVaza-SerpentCS PR #633 
- [ ] web_digital_sign PR #644 
- [ ] web_groupby_expand
- [ ] web_lead_funnel_chart
- [ ] web_one2many_kanban
- [ ] web_security_dialog
- [ ] web_widget_multi_image
- [ ] website_product_brand
- [x] ipushp PR #625
